version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/moul.io/depviz
    steps:
      - checkout
      - run: GO111MODULE=on go get -v -t -d ./...
      - run: go test -v ./...
